### ISSUE TITLE
Automatically generate copyedit note

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics#236]

**Comment by mazhang2718** [comment]
Problem: Drafting copy-edit e-mails for graphics can be fairly tedious in the graphics process, involving: copy-pasting from Aly's copyedit note, copy-pasting all the spreadsheet/graphic URLs, and copy-pasting all the spreadsheet data. Since this comes up every time we finish a graphic, it'd be nice to automate this process.

Solutions: We initially explored a browser-based solution, where pressing a button on the graphic page would copy the relevant information. However, for multiple graphics, navigating to each graphic page would still be tedious. Instead, we decided to go with a fabric command - this would allow us to compile the links/info from multiple graphics from a single command, which we could then easily paste into an e-mail. There are still things that we have to input manually, like the Seamus link, but there's not really a way to automate that (plus, those parts aren't as tedious as the others).

**Comment by ghing** [comment]
This is fully implemented and merged into master as of 05e151f.  Closing.
