### ISSUE TITLE
Update version of LESS we're using

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics#270]
We're at [1.7.0](https://github.com/nprapps/dailygraphics/blob/master/package.json), but the [current version](https://www.npmjs.com/package/less) is 3.0.4. Will this break anything?

- [x] test upgraded `less` locally
- [x] merge into `master`
- [x] merge into `childlink` branch
- [ ] alert dailygraphics users that they need to re-run `npm install` (either via Slack, Twitter, or email)

**Comment by mileswwatkins** [comment]
@alykat, if you want to test out the newer version, you could always run `npm install --save less` and see if that works as you build your resources. If it doesn't work simply, you can `npm install --save less@1.7.0` to revert.

As far as I can see, our use of `lessc` is pretty minimal, so it may actually just be a drop-in replacement. If not, likely simple poking to get it working. My only significant concern would be that it could introduce visual glitches into production, which we may not notice immediately (because of browser, screen size, etc); that said, the browser compatibility that it'll bring far outweighs that.
