### ISSUE TITLE
Disable gzip on deploy and prefer compression at the CDN level

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics#293]
Make it a boolean in `app_config.py` so folks who still want it can have it?

**Comment by mileswwatkins** [comment]
Since our `apps.npr.org` CloudFront is doing the GZIP compression itself, we should load uncompressed assets to S3. This entails turning off the compression step in our Python pipeline, similar to what I did in https://github.com/nprapps/elections18-graphics/commit/737d13b0288a6846d5203e0c51460c859372f0f1

**Comment by alykat** [comment]
Done in https://github.com/nprapps/dailygraphics/pull/310
